---
title: "ЗПШ-2017: теория вероятностей"
author: "Борис Демешев"
date: "3/27/2017"
output: html_document
lang: ru-RU
---

# Встреча 1

Пришло 9 школьников, 2 вожатых.

Техника решения задач и обозначения.

## Табличка

Составили табличку 2 на 2: сколько 10 классников и не 10 классников, сколько любят ваниальное мороженое, сколько не любят. Предположим, что один из нас (из 12) случайно заканчивает обедать первым. 

Какова вероятность, что это будет 10-классник? Любитель ванильного? Одновременно 10-классник И любитель ванильного?
10-классник ИЛИ любитель ванильного? 10-классник ЕСЛИ любитель ванильного?

Значки $\cap$, $\cup$, $|$.

### Дерево

Красная Шапочка (КШ) выбирает тропинки наугад и равновероятно.

Сначала дорога делится на три: L, M и R. L делится на две, R делится на 3, R делится на две.

Дороги LL, LR, ML, MM, MR патрулирует Волк.

Дороги LL, LR, MR ведут в Овраг.

Дороги ML, MM, RL, RR ведут к Бабушке.


События:

* Б — КШ попадёт к Бабушке
* В - КШ встретит Волка

P(Б)? P(В)? $P(\text{Б}\cap \text{В})$? $P(\text{Б} | \text{В})$?

